language: java
jdk:
- oraclejdk9
script: mvn package
deploy:
  provider: releases
  api_key:
    secure: SywLUEJlXpkeaxMuv4UuDkmsIqCPV6n5GOaibziBzDqB5Zl3xX1rOxe8XLfcJ8zYpMfwjSbwcdJLzZnO6/kE5advUFcQ0yt/1RHyyzfuddrArKURy0CARAUpSsVmy5LTYkhQxdw+XE7niYTVdvIHZmcgXLEXhEoUTxOPoso5xES0ZmmGWmq1MufsYrsNesAX7ubBiJ4Rsr/hJtF58x/ggbJTaKRYyVx8vWed4eGd4dDQlH/ycYPaAimdBJ7Cnsu4ZiejgCjHMDCp+HXY0yvpK3Q7I7lJ8Cdaty2kvVxXILvaxVTntcfLreBtLvq+8/rBRO97ryfHtzsMaPEEEdJAmblBkF9Pe/VgI4CiSmlaXTu9kdhBm8c3wotvRqpPXdSxAbUgfzkUVP3vvKoIhTwcG4UmIvvzwkM+jxO8ZcG1k4OJGAsRCN2OvUcEvPT4o2bpz175ybsiQCWe/O2FJRmo7P3XmWU+ebfV1EXcvzciBo66/3TRPO4Dz4DzXA8T4+QOAAAWq20AZtcD7lOmx7kQH2A8vJdEcXI5BIYxA0ioTtxOvMoqKA2nEz95vRocBNuVU6Xu4Aa5p0KLsbdHM+9m827G3W+sXAGve8XN+9WAK8dFLrf1pMYGtd9XxkmNJsD7tPv6sr7VU0Tn6n687S52DPOUbeRsApaMVDDdDuD/cV4=
  file_glob: true
  file: "target/ari*.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: AidosKuneen/aidos-node
    all_branches: true
